### ISSUE TITLE
Users in datastore having empty fields

### ISSUE THREAD

**Issue by adamsmlsn** [googleinterns/step21-2020#10]
I tried to log into the application using my adamsamuelson@google.com email and I was prompted to fill out the questionaire again (even thought I've already filled it out). By the second or third screen, I got a NullPointerException at InfoServlet.java:61. Upon inspecting the datastore, my entity properties were empty (probably due to improper handling in the code not producing filesys resilience). Also, the data fields in my profile just said "null".

I'm not sure why I was prompted to fill out the questionaire again but we need better handling in the code that accesses the datastore to keep properties from resetting. Also, if an entity property is blank, we should display something nicer than "null" in the user's profile.

**Comment by lailagamaleldin** [comment]
I think this might just be an issue with the version you're running since Datastore wasn't yet integrated. I just ran the code from PR #9 and didn't run into this issue.
